# Generated by Django 5.1.3 on 2024-11-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('release_date', models.DateField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_images/')),
            ],
        ),
    ]
